const dotenv = require('dotenv')
dotenv.config()
const express = require("express")
const app= express()
const captainRoutes = require('./routes/captain.routes')
const cookieParser = require('cookie-parser')
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(cookieParser())
const connect = require('./db/db')
connect()
app.use('/',captainRoutes)
const rabbitMq = require('./service/rabbit')
rabbitMq.connect()
module.exports = app;